name: Build and Package

on:
  push:
    branches:
      - main  # Run only on pushes to main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest GitHub Release Tag
        run: |
          RELEASE_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "latest")
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}

      # - name: Create Tarball
      #   run: tar -cvf app-${{ env.RELEASE_TAG }}.tar app
