name: Revert pushed commit

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

      release:
        description: 'enter the release'
        required: true
        default: 'Head'

jobs:
  revert_commit:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0


      - name: get the release hash
        id: out-hash
        run: |
          hash=$(git show-ref --tags -s ${{ github.event.inputs.release }})
          echo "release-hash=$hash" >> $GITHUB_OUTPUT
      
      
      
      - name: Revert pushed commit
        run: |
          git rev-parse HEAD
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          hash=$(git rev-parse HEAD)
          #git log --pretty=format:"%H" ${{ steps.out-hash.outputs.release-hash }}..HEAD
          commit_hashes=$(git log --pretty=format:"%H" ${{ steps.out-hash.outputs.release-hash }}..HEAD)
          array_length=${#commit_hashes[@]}
          echo "The length of the array is: $array_length"
          for commit_hash in $commit_hashes
          do
              # Your code here, for example, print each commit hash
              echo "Commit Hash: $commit_hash"
              git revert -m 1 $commit_hash
              #git show $commit_hash
          done

          git push
