name: 1_New version and deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:        
      - '*'  
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "bump-version"
 bump-version:
  runs-on: ubuntu-latest
  permissions:
      deployments: write
      contents: write
      statuses: write

  steps:

    - name: Checkout branch
      uses: actions/checkout@v4
  
    - name: Checkout repository
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        RELEASE_NOTES=$(gh release view --json body -q ".body")
        echo $RELEASE_NOTES
