name: 1_New version and deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:        
      - '*'  
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "bump-version"
 bump-version:
  runs-on: ubuntu-latest
  permissions:
      deployments: write
      contents: write
      statuses: write

  steps:

    - name: Checkout branch
      uses: actions/checkout@v4
    
    - name: Install MongoDB Shell
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh  

    - name: Get Repository Release Note
      id: get_note
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        RELEASE_NOTES=$(gh release view --json body -q ".body")
        echo "::set-output name=releasenote::$RELEASE_NOTES"

